backend:
  name: github
  repo: datadiversitylab/datadiversitylab.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: resilient-dasik-e50a03.netlify.app

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://datadiversitylab.github.io/assets/images/logos/logo-dark.svg

media_folder: 'src/assets/images/uploads'
public_folder: '/assets/images/uploads'

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    media_folder: '/src/assets/images/our-team'
    public_folder: '/assets/images/our-team'
    create: true
    identifier_field: memberName
    slug: '{{memberName}}'
    fields:
      - { label: 'Member Name', name: 'memberName', widget: 'string', required: true }
      - { label: 'Member title in the lab (current and former members)', name: 'memberTitle', widget: 'select', required: true, options: ['Intern', 'MS advising team', 'MSc capstone student', 'PhD student', 'PI', 'Postdoc', Staff, 'Undergraduate student', 'VIP student'], multiple: true }
      - { label: 'Alumni current position (former member)', name: 'currentPosition', widget: 'string', required: false }
      - { label: 'Member Date Start', name: 'memberDate', widget: 'string', required: false }
      - { label: 'Member Date End', name: 'memberDateEnd', widget: 'string', required: false }
      - { label: 'Member Bio', name: 'memberBio', widget: 'string', required: true }
      - { label: 'Role in the lab (tags)', name: 'tags', widget: 'select', default: ['Current'], required: true, options: ['Current', 'Former', 'Intern', 'MS advising team', 'MSc capstone student', 'PhD student', 'PI', 'Postdoc', Staff, 'Undergraduate student', 'VIP student'], multiple: true}
      - { label: 'Linkedin', name: 'linkedin', widget: 'string', required: false }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Github handle (not full link)', name: 'github', widget: 'string', required: false }
      - { label: 'Website', name: 'link', widget: 'string', required: false }
      - { label: 'Resume or CV', name: 'resume', widget: 'file', required: false, media_folder: '/src/assets/documents/our-team', public_folder: '/assets/documents/our-team' }
      - { label: 'Member Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
      - { label: 'Date', name: 'date', widget: 'datetime' }
  - name: 'publication'
    label: 'Publications'
    folder: 'src/publications'
    media_folder: '/src/assets/images/publications'
    public_folder: '/assets/images/publications'
    create: true
    identifier_field: publicationTitle
    slug: '{{publicationTitle}}'
    fields:
      - { label: 'Publication Title', name: 'publicationTitle', widget: 'markdown', required: true }
      - { label: 'Author', name: 'publicationAuthor', widget: 'string', required: false }
      - { label: 'Year', name: 'publicationDate', widget: 'string', required: false }
      - { label: 'Month', name: 'publicationMonth', widget: 'select', options: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], required: false }
      - { label: 'Journal Name', name: 'publicationType', widget: 'string', required: false }
      - { label: 'Abstract', name: 'publicationAbstract', widget: 'markdown', required: true }
      - { label: 'Keywords', name: 'tags', widget: 'list', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'PDF', name: 'pdfDocument', widget: 'file', required: false, media_folder: '/src/assets/documents/publications', public_folder: '/assets/documents/publications'}
      - { label: 'Badge', name: 'badgeImage', widget: 'string', required: false }
      - { label: 'PDF Url', name: 'pdfLink', widget: 'string', required: false }
      - { label: 'Web Url', name: 'webLink', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'grants'
    label: 'Grants'
    folder: 'src/grants'
    media_folder: '/src/assets/images/grants'
    public_folder: '/assets/images/grants'
    create: true
    identifier_field: grantName
    slug: '{{grantName}}'
    fields:
      - { label: 'Name', name: 'grantName', widget: 'string', required: true }
      - { label: 'Subaward', name: 'subawardAmount', widget: 'string', required: false }
      - { label: 'Years', name: 'grantYears', widget: 'string', required: false }
      - { label: 'PI', name: 'pi', widget: 'string', required: false }
      - { label: 'Co-PI(s)', name: 'copi', widget: 'list', required: false }
      - { label: 'Total amount', name: 'grantAmount', widget: 'string', required: false }
      - { label: 'Description', name: 'grantDesc', widget: 'string', required: false }
      - { label: 'Funder', name: 'tags', widget: 'list', required: true }
      - { label: 'Document', name: 'document', widget: 'file', required: false, media_folder: '/src/assets/documents/grants', public_folder: '/assets/documents/grants' }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Member Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'softwares'
    label: 'Software'
    folder: 'src/softwares'
    media_folder: '/src/assets/images/softwares'
    public_folder: '/assets/images/softwares'
    create: true
    identifier_field: Name
    slug: '{{Name}}'
    fields:
      - { label: 'Name', name: 'Name', widget: 'string', required: true }
      - { label: 'Authors', name: 'authors', widget: 'list', required: true }
      - { label: 'Description', name: 'Description', widget: 'markdown', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Github', name: 'github', widget: 'string', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'databases'
    label: 'Databases'
    folder: 'src/databases'
    media_folder: '/src/assets/images/databases'
    public_folder: '/assets/images/databases'
    create: true
    identifier_field: Name
    slug: '{{Name}}'
    fields:
      - { label: 'Name', name: 'Name', widget: 'string', required: true }
      - { label: 'Authors', name: 'authors', widget: 'list', required: true }
      - { label: 'Description', name: 'Description', widget: 'markdown', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Github', name: 'github', widget: 'string', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false }
  - name: 'socials'
    label: 'Socials'
    folder: 'src/socials'
    media_folder: '/src/assets/images/socials'
    public_folder: '/assets/images/socials'
    create: true
    identifier_field: publicationTitle
    slug: '{{publicationTitle}}'
    fields:
      - { label: 'Name', name: 'publicationTitle', widget: 'string', required: true }
      - { label: 'Location', name: 'Location', widget: 'string', required: false }
      - { label: 'Year', name: 'publicationDate', widget: 'list', required: true }
      - { label: 'Month', name: 'publicationMonth', widget: 'select', options: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], required: true }
      - { label: 'Description', name: 'publicationAbstract', widget: 'string', required: false }
      - { label: 'Images', name: 'images', widget: 'list', required: false, field: { label: 'Image', name: 'image', widget: 'image' } }
      - { label: 'Tag', name: 'tags', widget: 'string', required: true }
      - { label: 'Link', name: 'webLink', widget: 'string', required: false }
      - { label: 'PDF', name: 'pdfDocument', widget: 'string', required: false }
  - name: 'news'
    label: 'News'
    folder: 'src/news'
    media_folder: '/src/assets/images/news'
    public_folder: '/assets/images/news'
    create: true
    summary: "{{Name}} - {{tags[0]}}"
    identifier_field: body
    sortable_fields: ['tags']
    slug: '{{Name}}-{{tags}}'
    fields:
      - { label: 'Name', name: 'Name', widget: 'string', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Order',name: 'order', widget: 'number', required: false }
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "inthenews"
    label: "In the News"
    folder: "src/inthenews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "newsTitle", widget: "string" }
      - { label: "Outlet", name: "Outlet", widget: "string", required: true }
      - { label: "Year", name: "tags", widget: "list", required: true }
      - { label: "Semester", name: "newsDate", widget: "string" , required: true}
      - { label: "Description", name: "newsDesc", widget: "text" }
      - { label: "Link to article", name: "link", widget: "string", required: false }
      - { label: "Document (PDF)", name: "document", widget: "file", required: false }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: "Image", name: "", widget: "image" }
        }
  - name: 'jobs'
    label: 'Jobs'
    folder: 'src/jobs'
    media_folder: '/src/assets/images/jobs'
    public_folder: '/assets/images/jobs'
    create: true
    identifier_field: jobTitle
    slug: '{{jobTitle}}'
    fields:
      - { label: 'Job Title', name: 'jobTitle', widget: 'string', required: true }
      - { label: 'Job Start Date', name: 'jobStartDate', widget: 'string', required: false }
      - { label: 'Job Apply By', name: 'jobApplyBy', widget: 'string', required: false }
      - { label: 'Job Description', name: 'jobDesc', widget: 'markdown', required: false }
      - { label: 'Job Pdf', name: 'jobPdf', widget: 'file', required: false, media_folder: '/src/assets/documents/jobs', public_folder: '/assets/documents/jobs' }
      - { label: 'Order',name: 'order', widget: 'number', required: false }
  - name: 'collaborators'
    label: 'Collaborators'
    folder: 'src/collaborators'
    media_folder: '/src/assets/images/collaborators'
    public_folder: '/assets/images/collaborators'
    create: true
    identifier_field: collaboratorName
    slug: '{{collaboratorName}}'
    fields:
      - { label: 'Collaborator Name', name: 'collaboratorName', widget: 'string', required: true }
      - { label: 'Collaborator Title', name: 'collaboratorTitle', widget: 'string', required: false }
      - { label: 'Collaborator Date', name: 'collaboratorDate', widget: 'string', required: false }
      - { label: 'Collaborator Bio', name: 'collaboratorBio', widget: 'string', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Linkedin', name: 'linkedin', widget: 'string', required: false }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Resume', name: 'resume', widget: 'string', required: false }
      - { label: 'Member Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
      - { label: 'Date', name: 'date', widget: 'datetime' }
  - name: 'teachingExperience'
    label: 'Teaching Experience'
    folder: 'src/teachingExperience'
    media_folder: '/src/assets/images/teaching-experience'
    public_folder: '/assets/images/teaching-experience'
    create: true
    identifier_field: title
    slug: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Rows', name: 'rows', widget: 'list', required: true, fields: [
          { label: 'Year-Semester', name: 'yearSemester', widget: 'string', required: true },
          { label: 'Course', name: 'course', widget: 'string', required: true },
          { label: 'Role', name: 'role', widget: 'string', required: true },
          { label: 'Number of Students', name: 'studentsAmount', widget: 'number', required: true }
        ]
      }
      - { label: 'Year', name: 'year', widget: 'number', required: true }
  - name: 'labPolicies'
    label: 'Lab Policies'
    folder: 'src/labPolicies'
    media_folder: '/src/assets/images/lab-policies'
    public_folder: '/assets/images/lab-policies'
    create: true
    identifier_field: title
    slug: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'body', widget: 'markdown', required: true }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'transparencys'
    label: 'Transparency cards'
    folder: 'src/transparencys'
    media_folder: '/src/assets/images/transparencys'
    public_folder: '/assets/images/transparencys'
    create: true
    identifier_field: title
    slug: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Year Range', name: 'yearRange', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'studentEvaluations'
    label: 'Student Evaluations'
    folder: 'src/studentEvaluations'
    media_folder: '/src/assets/images/student-evaluations'
    public_folder: '/assets/images/student-evaluations'
    identifier_field: title
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Order', name: 'order', widget: 'number', required: false }
  - name: 'pages'
    label: "Home page"
    media_folder: '/src/assets/images'
    public_folder: '/assets/images'
    files:
      - label: "Home Page"
        name: "Home"
        file: "src/_data/home.json"
        fields:
          - label: Title
            name: title
            widget: string
          - label: sub title
            name: subTitle
            widget: string
          - label: Description
            name: description
            widget: markdown
          - label: Buttons
            name: buttons
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - label: Background Images
            name: backgroundImages
            widget: list
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
          - label: Cards
            name: cards
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
  - name: 'logos'
    label: 'Logos'
    folder: 'src/logos'
    media_folder: '/src/assets/images/logos'
    public_folder: '/assets/images/logos'
    create: false
    delete: false
    identifier_field: title
    slug: '{{title}}'
    fields:
      - { label: 'Logo Image', name: 'image', widget: 'image', required: true }
  - name: 'favicons'
    label: 'Favicons'
    media_folder: '/src/assets/favicons'
    public_folder: '/assets/favicons'
    files:
      - label: "Favicons refer to directions inside"
        name: "Favicons"
        file: "src/_data/favicons.json"
        fields:
          - label: Directions
            name: readonlyField
            widget: text
            required: false
          - label: Favicon ICO
            name: faviconIco
            widget: image
          - label: Favicon 32x32
            name: faviconBrowser32
            widget: image
          - label: Favicon 16x16
            name: faviconBrowser16
            widget: image
          - label: Apple Touch Icon
            name: appleTouchIcon
            widget: image
          - label: Android Chrome 192
            name: androidChrome192
            widget: image
          - label: Android Chrome 384
            name: androidChrome384
            widget: image
